---
group:
  # python repo's with Renovate
  - files:
      # Specific
      - source: python_package/renovate.json
        dest: .github/renovate.json
      # General - files and folders
      - source: python_package/.gitignore
        dest: .gitignore
      - source: python_package/.yamllint
        dest: .yamllint
      # .github folder + workflows
      - source: github/
        dest: .github/
    repos: |
      klaasnicolaas/python-antwerpen
      klaasnicolaas/python-arnhem
      klaasnicolaas/python-brussel
      klaasnicolaas/python-dresden
      klaasnicolaas/python-dusseldorf
      klaasnicolaas/python-easyenergy
      klaasnicolaas/python-eindhoven
      klaasnicolaas/python-eiswarnung
      klaasnicolaas/python-energyzero
      klaasnicolaas/python-gridnet
      klaasnicolaas/python-hamburg
      klaasnicolaas/python-koeln
      klaasnicolaas/python-liege
      klaasnicolaas/python-muenster
      klaasnicolaas/python-namur
      klaasnicolaas/python-odp-amsterdam
      klaasnicolaas/python-odp-gent
      klaasnicolaas/python-omnikinverter
      klaasnicolaas/python-p1monitor
      klaasnicolaas/python-zurich

  # NIPKaart projects - general
  - files:
      # General - files and folders
      - source: python_package/.gitignore
        dest: .gitignore
      - source: python_package/.yamllint
        dest: .yamllint
      # .github folder + workflows
      - source: github/
        dest: .github/
    repos: |
      NIPKaart/disabled-parking
      NIPKaart/offstreet-parking

  # python repo's with Dependabot
  # - files:
  #     # Specific
  #     - source: python_package/dependabot.yml
  #       dest: .github/dependabot.yml
  #     # General - files and folders
  #     - source: python_package/.gitignore
  #       dest: .gitignore
  #     - source: python_package/.yamllint
  #       dest: .yamllint
  #     - source: github/
  #       dest: .github/
  #   repos: |

# Copier template
klaasnicolaas/pypackage-template:
  ### Template stuff ###
  - source: python_package/.gitignore
    dest: template/.gitignore
  - source: python_package/.yamllint
    dest: template/.yamllint
  # .github folder + workflows
  - source: github/
    dest: template/.github/
  ### Project general - single files ###
  - source: github/release-drafter.yml
    dest: .github/release-drafter.yml
  - source: github/labels.yml
    dest: .github/labels.yml
  - source: python_package/.gitignore
    dest: .gitignore
  - source: python_package/.yamllint
    dest: .yamllint
  ### Project general - workflows ###
  - source: github/workflows/
    dest: .github/workflows/
