---
group:
  # NIPKaart projects - general
  - files:
      # General - files and folders
      - source: nipkaart/.gitignore
        dest: .gitignore
      - source: python_package/.yamllint
        dest: .yamllint
      # .github folder + workflows
      - source: github/
        dest: .github/
    repos: |
      NIPKaart/disabled-parking
      NIPKaart/offstreet-parking
