---
group:
  # python repo's with Renovate
  - files:
      # Specific
      - source: python/renovate.json
        dest: .github/renovate.json
      # General - files and folders
      - source: python/.gitignore
        dest: .gitignore
      - source: github/
        dest: .github/
    repos: |
      klaasnicolaas/python-arnhem
      klaasnicolaas/python-easyenergy
      klaasnicolaas/python-energyzero
      klaasnicolaas/python-p1monitor

  # python repo's with Dependabot
  - files:
      # Specific
      - source: python/dependabot.yml
        dest: .github/dependabot.yml
      # General - files and folders
      - source: python/.gitignore
        dest: .gitignore
    repos: |
      klaasnicolaas/python-antwerpen
      klaasnicolaas/python-brussel
      klaasnicolaas/python-dresden
      klaasnicolaas/python-dusseldorf
      klaasnicolaas/python-eindhoven
      klaasnicolaas/python-eiswarnung
      klaasnicolaas/python-gridnet
      klaasnicolaas/python-hamburg
      klaasnicolaas/python-koeln
      klaasnicolaas/python-liege
      klaasnicolaas/python-muenster
      klaasnicolaas/python-namur
      klaasnicolaas/python-odp-amsterdam
      klaasnicolaas/python-odp-gent
      klaasnicolaas/python-omnikinverter
      klaasnicolaas/python-zurich

# Copier template
klaasnicolaas/pypackage-template:
  # Template stuff
  - source: github/
    dest: template/.github/
  - source: python/.gitignore
    dest: template/.gitignore
  # Project general - single files
  - source: github/release-drafter.yml
    dest: .github/release-drafter.yml
  - source: github/labels.yml
    dest: .github/labels.yml
  - source: python/.gitignore
    dest: .gitignore
  # Project general - folders
  - source: github/workflows/
    dest: .github/workflows/
